#!/bin/sh
# -*- coding: us-ascii-unix -*-

# Copyright (C) 2016 Osmo Salomaa
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

OPTIND=1
SIZE=128

while getopts i:o:s: OPTION; do
    case "$OPTION" in
        i)  INPUT="$OPTARG" ;;
        o) OUTPUT="$OPTARG" ;;
        s)   SIZE="$OPTARG" ;;
    esac
done
if [ ! -f "$INPUT" ] || [ -z "$OUTPUT" ] || [ -z "$SIZE" ]; then
    echo "Usage: mpv-thumbnailer -i VIDEO -o THUMBNAIL [-s SIZE]

VIDEO is the input file to generate a thumbnail from and THUMBNAIL is
the output image file to write. SIZE is optional and defaults to 128."

    exit 1
fi

TEMPDIR=$(mktemp -d)

# Seeking might fail with some semi-broken files.
# Fall back to thumbnailing from the start.
for START in 20% 0; do
    mpv --really-quiet \
        --no-config \
        --vo=image \
        --vo-image-format=png \
        --vo-image-png-compression=0 \
        --vo-image-png-filter=0 \
        --vo-image-outdir=$TEMPDIR \
        --aid=no \
        --sid=no \
        --start=$START \
        --frames=3 \
        "$INPUT"

    [ $(ls $TEMPDIR | wc -l) = 3 ] && break;
done

convert -thumbnail "$SIZEx$SIZE>" $TEMPDIR/*3.png "$OUTPUT"
rm $TEMPDIR/*.png && rmdir $TEMPDIR
